Update README.md
GSG-FC02/Bonappetit pull request #5
Opened 2021-04-10 11:51 UTC by sajarantisi

2021-04-10 12:14 UTC, AlaaTaima commented on README.md
> +* it would be nice if the website have a section to get me the restaurants in some location and information about this restaurant in case I want to eat outside my house.
**User stories should explain the services that a user can use as a list, 
So, Fix the syntax of it as the following :** 

* As a user I can, find all recipes from the ingredients that I have in my fridge to make it easy to me decide what I want meal for today.

// fix the rest of them.

2021-04-10 12:16 UTC, Nour-Nasr approved these changes, later dismissed

2021-04-10 12:16 UTC, AlaaTaima requested changes
**Fix user story syntax**

2021-04-10 12:16 UTC, suhail-radwan approved these changes, later dismissed

2021-04-10 12:24 UTC, Nour-Nasr approved these changes

2021-04-11 09:56 UTC, suhail-radwan approved these changes

2021-04-11 10:00 UTC, AlaaTaima approved these changes

2021-04-11 10:00 UTC, merged